on: [push]  

jobs:
  build-and-test:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2

      - name: Build with Maven Wrapper
        run: ./mvnw clean package

      - name: Run tests
        run: ./mvnw test
