name: Build and Test

on:
  push:
    branches:
      - main      # or your default branch name
  workflow_dispatch:   # lets you trigger it by hand

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ./mvnw clean package
      - name: Test
        run: ./mvnw test
