name: Build and Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: employees-main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with Maven Wrapper
        run: ./mvnw clean package

      - name: Run tests
        run: ./mvnw test
